# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99d09f4c5bb71b86b6b443fcd7601faeed8494539f927b840eea2656f1ee877882d1e5012306e7b409d7e1e5ef8d0d353e0954c92ada4c9eaa1433c840bc6932

test:
  secret_key_base: b9e6c95e99830011c20c7ae8a028a91dcd4e34dd0cf7543378cd6f2728bc85b485ac7ca07af790960cde6793ed6081884d12b9b2709d572e972460feee442041

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
